# Generated by Django 5.2.7 on 2025-12-07 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParametresFiscaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeTaxe', models.CharField(max_length=30)),
                ('taux', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.commande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='api.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(max_length=50)),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='api.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('courriel', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('comptable', 'Comptable'), ('magasinier', 'Magasinier'), ('admin', 'Admin'), ('gestionnaire', 'Gestionnaire'), ('agentclientele', 'Agent du service à la clientèle')], max_length=30)),
                ('panier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.panier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('courriel', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('prospect', 'Prospect'), ('actif', 'Actif'), ('fidele', 'Fidèle'), ('inactif', 'Inactif')], default='prospect', max_length=10)),
                ('panier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.panier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='ParametresFiscaux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.parametresfiscaux'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ParametresFiscaux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.parametresfiscaux'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=30)),
                ('coutAchat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('seuilReapprovisionnement', models.PositiveIntegerField()),
                ('quantite_dispo', models.PositiveIntegerField()),
                ('stockMinimum', models.PositiveIntegerField()),
                ('prixVente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorieProduit', models.CharField(max_length=100)),
                ('delaiLivraison', models.PositiveIntegerField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='api.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='mouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('dateMouvement', models.DateTimeField()),
                ('estAjout', models.BooleanField(default=True)),
                ('motif', models.CharField(max_length=1000)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='itemPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='api.client')),
                ('facture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateActivite', models.DateTimeField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='api.client')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='api.employe')),
                ('vente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vente')),
            ],
        ),
    ]
