# Generated by Django 5.2.7 on 2025-12-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produit_image_alter_produit_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='commande',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achat', to='api.commande'),
        ),
    ]
