# Generated by Django 5.2.7 on 2025-12-20 17:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_achat_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='ParametresFiscaux',
        ),
        migrations.AddField(
            model_name='commande',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='tps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='tvq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RECEPTIONNEE', 'Réceptionnée')], default='EN_ATTENTE', max_length=30),
        ),
        migrations.CreateModel(
            name='PaiementAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé')], default='EN_ATTENTE', max_length=20)),
                ('mode', models.CharField(default='carte', max_length=50)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiementAchat', to='api.commande')),
            ],
        ),
    ]
