# Generated by Django 5.2.7 on 2025-12-20 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_commande_parametresfiscaux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
