# Generated by Django 5.2.7 on 2025-12-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_commande_date_commande_commande_date_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementachat',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
