# Generated by Django 5.2.7 on 2025-12-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_facture_statut_facture_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(default='PAYEE', max_length=20),
        ),
    ]
