# Generated by Django 5.2.7 on 2025-12-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_commandeclient_lignecommandeclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='date_fermeture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='date_preparation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
