# Generated by Django 5.2.7 on 2025-12-22 04:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_commandeclient_date_fermeture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions', to='api.client')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='api.commandeclient')),
            ],
        ),
    ]
