# Generated by Django 5.2.7 on 2025-12-22 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='derniere_activite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activite',
            name='dateActivite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
