# Generated by Django 5.2.7 on 2025-12-22 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_client_derniere_activite_alter_activite_dateactivite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='derniere_activite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
