# Generated by Django 5.2.7 on 2025-12-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_client_derniere_activite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='vente',
        ),
        migrations.AddField(
            model_name='activite',
            name='commande_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='api.commandeclient'),
        ),
        migrations.AddField(
            model_name='activite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='crm/'),
        ),
        migrations.AddField(
            model_name='activite',
            name='page_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='type',
            field=models.CharField(choices=[('VISITE_SITE', 'Visite du site'), ('VISITE_PAGE', "Visite d'une page"), ('COMMANDE', 'Commande'), ('COURRIEL', 'Courriel'), ('APPEL', 'Appel téléphonique'), ('PDF', 'Document PDF'), ('NOTE', 'Note manuelle')], default='NOTE', max_length=30),
        ),
    ]
